name:                haskell-snake
version:             0.1.0.0
github:              "ip/haskell-snake"
license:             MIT
author:              "Ivan Perevezentsev"
maintainer:          "perevezentsev@protonmail.com"
copyright:           "2019 Ivan Perevezentsev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Snake game in Haskell
# category:            Games

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ip/haskell-snake>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - random
    - sdl2
    - text

executables:
  haskell-snake-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-snake
    - random

tests:
  haskell-snake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-snake
